export const Global = {
    EVENT_SLIDER_CHOOSE_TAB: 'EVENT_SLIDER_CHOOSE_TAB-tab',
    EVENT_CHOOSE_TAB: 'EVENT_CHOOSE_TAB_',
    EVENT_CHOOSE_TAB_1: 'EVENT_CHOOSE_TAB_1',
    EVENT_CHOOSE_TAB_2: 'EVENT_CHOOSE_TAB_2',
    EVENT_CHOOSE_TAB_3: 'EVENT_CHOOSE_TAB_3',
    EVENT_CHOOSE_TAB_4: 'EVENT_CHOOSE_TAB_4',

    EVENT_ADDRESS_START: 'EVENT_ADDRESS_START',
    EVENT_ADDRESS_END: 'EVENT_ADDRESS_END',

    STORAGE_CITY: 'city',
    STORAGE_MEMBER: 'member',

    MAN: '男',
    WOMAN: '女',

    //默认经纬度
    DEFAULT_LNG: 113.36967,
    DEFAULT_LAT: 23.132384,

    Success: 'success',
    Failure: 'failure',
};
